# Generated by Django 3.2.15 on 2023-05-10 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, default='admin', max_length=100)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('content', models.CharField(blank=True, default='', max_length=500)),
                ('tags', models.CharField(blank=True, default='', max_length=500)),
            ],
        ),
    ]
